LamMdlBundle_homepage:
    pattern:  /
    defaults: { _controller: LamMdlBundle:Default:index }
LamMdlBundle_formationinformatique:
    pattern:  /fi
    defaults: { _controller: LamMdlBundle:FormationInformatique:liste }
    
LamMdlBundle_contenuformationinformatique:
    pattern:  /contenufi/{num}
    defaults: { _controller: LamMdlBundle:FormationInformatique:contenuinfo , num:1}

LamMdlBundle_datesstageinfo:
    pattern:  /datesstageinfo/{num}
    defaults: { _controller: LamMdlBundle:FormationInformatique:stage , num:1}


LamMdlBundle_formationsport:
    pattern:  /fs
    defaults: { _controller: LamMdlBundle:FormationSport:liste }    
    
LamMdlBundle_contenuformationsport:
    pattern:  /contenufs/{num}
    defaults: { _controller: LamMdlBundle:FormationSport:contenusport , num:1}

LamMdlBundle_datesstagesport:
    pattern:  /datesstagesport/{num}
    defaults: { _controller: LamMdlBundle:FormationSport:stage , num:1}
    
LamMdlBundle_Form:
    pattern:  /form
    defaults: { _controller: LamMdlBundle:Formulaire:ajout }
    
LamMdlBundle_inscriptionOrganisme:
    pattern:  /inscription_organisme
    defaults: { _controller: LamMdlBundle:Formulaire:inscriptionOrga }
    
LamMdlBundle_Verification:
    pattern:  /x
    defaults: { _controller: LamMdlBundle:Default:verif }
    
