<?php

namespace Lam\MdlBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionRepository extends EntityRepository
{
    
    public function NbInscriptFormation($nbInscit,$idFormation)
    {
    $query = $this->_em->createQuery("update LamMdlBundle:Formation f set f.nbinscrits='$nbInscit'   where f.id='$idFormation' ");
    $resultats = $query->execute();
    return $resultats;
  }
    
    
}