<?php

namespace Lam\MdlBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganismeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganismeRepository extends EntityRepository
{
    
    public function verificationMdp($idOrga){
     $query = $this->_em->createQuery("SELECT mdpOrnisme FROM LamMdlBundle:organisme   where organisme.id='$idOrga'");
    $resultats = $query->getResult();
    return $resultats;
    
    
    }
    
    
    public function listeOrga()
    {
        
        $query = $this->_em->createQuery("SELECT nom_Ornisme FROM LamMdlBundle:organisme ");
    $resultats = $query->getResult();
    return $resultats;
    }
}